#include QMK_KEYBOARD_H

// Layer names
#define _LAYER0 0
#define _LAYER1 1
#define _LAYER2 2
#define _LAYER3 3

// Layer switching macros
#define TL_LOWR   MO(_LAYER1)    // Momentary Layer 1
#define TL_UPPR   MO(_LAYER2)    // Momentary Layer 2
#define TL_UPPR_2 TG(_LAYER3)    // Toggle Layer 3 (Gaming)

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

[_LAYER0] = LAYOUT_rigby(
  QK_GESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_BSPC,
  KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_ENT,
  KC_LSFT, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT,
  KC_LCTL, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_HOME, TL_UPPR_2, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_DEL,
  KC_LGUI, TL_LOWR, KC_SPC, KC_BSPC, TL_UPPR, KC_RALT
),

[_LAYER1] = LAYOUT_rigby(
  KC_TILD, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_PGUP,
  KC_GRV, KC_TRNS, KC_UP, KC_TRNS, QK_BOOT, KC_TRNS, KC_TRNS, KC_P7, KC_P8, KC_P9, KC_P0, KC_PGDN,
  KC_DEL, KC_LEFT, KC_DOWN, KC_RGHT, KC_TRNS, KC_LBRC, KC_RBRC, KC_P4, KC_P5, KC_P6, KC_PLUS, KC_PIPE,
  RM_NEXT, EE_CLR, KC_TRNS, KC_TRNS, KC_TRNS, KC_LCBR, KC_LPRN, KC_RPRN, KC_RCBR, KC_P1, KC_P2, KC_P3, KC_MINS, KC_TRNS,
  KC_TRNS, KC_TRNS, KC_DEL, KC_DEL, KC_TRNS, KC_P0
),

[_LAYER2] = LAYOUT_rigby(
  KC_F12, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11,
  RM_TOGG, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, QK_BOOT,
  RM_NEXT, KC_MPRV, KC_MNXT, KC_VOLU, KC_PGUP, KC_UNDS, KC_EQL, KC_HOME, RM_HUEU, RM_SATU, RM_VALU, KC_BSLS,
  KC_MUTE, KC_MSTP, KC_MPLY, KC_VOLD, KC_PGDN, KC_MINS, KC_LPRN, KC_TRNS, KC_PLUS, KC_END, RM_HUED, RM_SATD, RM_VALD, EE_CLR,
  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
),

[_LAYER3] = LAYOUT_rigby(
  KC_ESC, KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_6, KC_7, KC_8, KC_9, KC_0, KC_BSPC,
  KC_TAB, KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_ENT,
  KC_NO, KC_LSFT, KC_A, KC_S, KC_D, KC_F, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT,
  KC_NO, KC_LCTL, KC_Z, KC_M, KC_U, KC_NO, KC_NO, KC_NO, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_DEL,
  KC_LGUI, KC_LALT, KC_SPC, KC_SPC, TG(_LAYER3), KC_RALT // <- use TG here to toggle off too
)
};
